<section class="about" id="about">
    <div class="container">
        <h2 class="section-title">
            We're group of 5 guys with passion to programming and what you can see in the picture :D</h2>
        <p class="section-intro">This App was created as a group project during java bootcamp.<br> It's purpose is to create
            an interactive drinks library with many functions.</br> In our search-engine you can choose
            from verity of recipes or even add your own.</p>
    </div>
</section>