<section class="contact" id="contact">
    <div class="container">
        <h2 class="section-title">CONTACT</h2>
        <ul class="social-links">
            <li><a href="#"><i class="fab fa-facebook-square"></i></a></li>
            <li><a href="#"><i class="fab fa-twitter-square"></i></a></li>
            <li><a href="#"><i class="fab fa-instagram-square"></i></a></li>
        </ul>
    </div>
</section>