<!-- css -->
<link href="styles/style.css" rel="stylesheet" type="text/css">
<link src="https://use.fontawesome.com/releases/v5.6.0/css/all.css">
<link href="https://use.fontawesome.com/releases/v5.6.0/css/all.css" rel="stylesheet" type="text/css">
<link href="https://unpkg.com/flickity@2/dist/flickity.min.css" rel="stylesheet" type="text/css">
<link href="https://use.fontawesome.com/releases/v5.14.0/css/all.css" rel="stylesheet" type="text/css">
