<html>
<head>
    <meta charset="UTF-8">
    <title> Goodbye </title>

    <#include "css.ftlh">

</head>
<body>



<section class="splash"
         style="background-image: url('https://images.pexels.com/photos/519/light-sign-typography-lighting.jpg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940');">
    <div class="page-intro">

        <h1 class="main-title"> COME BACK WHEN YOU OVER 18+ </h1>

    </div>
</section>

<#include "contact.ftlh">

<#include "footer.ftlh">

</body>
</html>